# vim:ft=ansible:
---
- hosts: webservers
  remote_user: ubuntu
  sudo: yes
  roles:
    - common
    - nodejs
    - { role: nginx, tags: ['nginx'] }
    - { role: ripple-rest, tags: ['ripple-rest'] }
    - { role: newrelic-sysmon, tags: ['newrelic'] }
