---
- name: restart rest
  service: name=ripple-rest state=restarted

- name: restart monit
  service: name=monit state=restarted

- name: check rest
  shell: status ripple-rest | grep -qw running; echo $?
  register: rest_status
  failed_when: rest_status.stdout != '0'

