---
- name: Create the ripple-rest user
  group: >
    name='{{rest.group }}'
    state=present

- name: Create the ripple-rest group
  user: >
    name='{{ rest.user }}'
    state=present
    group='{{ rest.group }}'

- name: Check if running for the first time
  stat: path='{{ rest.path }}'/releases
  register: check_rest_path

- name: Update or check out Ripple-REST for the first time
  include: update.yml
  when: update == True or check_rest_path.stat.isdir is not defined

- name: Create the deployment shared logs directory
  file: >
    path='{{ rest.log_dir }}'
    owner='{{ rest.user }}'
    group='{{ rest.group }}'
    state=directory
    mode=755

- name: Copy ripple-rest upstart script
  template: >
    src=upstart.j2
    dest=/etc/init/ripple-rest.conf
    mode=644
    owner=root
    group=root
  notify: restart rest

- name: Copy ripple-rest monit script
  template: >
    src=monit.j2
    dest=/etc/monit/conf.d/ripple-rest
    mode=644
    owner=root
    group=root
  notify: reload monit

- name: Log rotation
  template: >
    src=logrotate.j2
    dest=/etc/logrotate.d/ripple-rest
    mode=644
    owner=root
    group=root

- name: Include New Relic Node Agent
  include: newrelic.yml
  tags:
    - newrelic

- name: Ensure init.d script absent
  file: path=/etc/init.d/ripple-rest state=absent

- name: Start Rest
  service: name=ripple-rest state=started

- name: Start Monit
  service: name=monit state=started

- name: Start Nginx
  service: name=nginx state=started

- name: Check ripple-rest is running
  command: /bin/true
  notify: check rest

